### ISSUE TITLE
why the card background color  is grey ? how to change it?

### ISSUE THREAD

**Issue by hymanhk** [bedardjo/playing_cards#12]
![1668059285351](https://user-images.githubusercontent.com/73326200/201010810-9bd81fe7-5242-4dd0-9283-f22bf5be779b.png)

**Comment by xvadim** [comment]
I got the same issue when set `useMaterial3: true` for ThemeData.
The PlayingCard widget uses the Card widget, which background depends on this parameter.

**Comment by bedardjo** [comment]
@xvadim is right, this is due to some new material styling. Added the ability to customize color and surface tint color (with white defaults), which should fix this.

**Comment by bedardjo** [comment]
Please reopen if any issues, thanks!
