### ISSUE TITLE
FlatCardFan crashes when there is one card

### ISSUE THREAD

**Issue by MatteoDiTucci** [bedardjo/playing_cards#18]
**Summary**
FlatCardFan crashes when there is only one card.

**Library version**
0.3.1+9

**How to reproduce**
The following code does not render any card:

`FlatCardFan(
      children: [
        PlayingCardView( card: PlayingCard(Suit.hearts, CardValue.ace)),
      ],
    )`
    
**Analysis**
I noticed that the source code for the library version `0.3.1+9` comes from the branch `null-safety-impl`. In this branch FlatCardFan performs a division by zero which is the [cause](https://github.com/bedardjo/playing_cards/blob/null-safety-impl/lib/src/views/flat-card-fan.dart#L19) of the bug. 

However, the `master` branch fixes this bug with a [nice ternary operator](https://github.com/bedardjo/playing_cards/blob/master/lib/src/views/flat_card_fan.dart#L24)!

**Question**

My assumption is that the branch `null-safety-impl` is what is released on `pub.dev`, while `master` branches contains yet to be released functionalities (sorry in case this assumption from my side is wrong).

Given the above assumption, I was wondering if it was possible to merge the `master` version of `FlatCardFan` into the `null-safety-impl` branch. If you think it is fine, I am very happy to do the pull request myself.

Thank you

**Notes**
Thank you very much for maintaining this library. I have been using it since some days and I like it very much.

**Comment by bedardjo** [comment]
Thanks! You are correct, the fix was on master (contributed by a community member!). I've published master and this should be resolved.

**Comment by bedardjo** [comment]
Closing.
